import { Analytics } from '@vercel/analytics/next'
import type { Metadata, Viewport } from 'next'
import { Cormorant_Garamond, DM_Sans } from 'next/font/google'
import './globals.css'

const serif = Cormorant_Garamond({ subsets: ['latin'], variable: '--font-cormorant', display: 'swap' })
const sans = DM_Sans({ subsets: ['latin'], variable: '--font-dm-sans', display: 'swap' })
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://companios.example'
const seoKeywords = [
  'male companion Bhopal', 'male companion in Bhopal', 'male companionship Bhopal', 'male companionship service Bhopal', 'professional male companion Bhopal', 'male companion service Bhopal', 'male companion agency Bhopal', 'male companion booking Bhopal', 'male companion hire Bhopal', 'hire a male companion Bhopal', 'male companion for hire Bhopal', 'male companion near me Bhopal', 'male companion services near me', 'professional companion Bhopal', 'professional companionship Bhopal', 'companionship service Bhopal', 'private companion Bhopal', 'personal companion Bhopal', 'social companion Bhopal', 'gentleman companion Bhopal', 'male social companion Bhopal', 'male personal companion Bhopal', 'companion services Bhopal', 'companion agency Bhopal', 'companion booking Bhopal',
  'male escort Bhopal', 'male escorts Bhopal', 'male escort in Bhopal', 'male escort service Bhopal', 'male escort services Bhopal', 'professional male escort Bhopal', 'male escort agency Bhopal', 'male escort booking Bhopal', 'male escort near me Bhopal', 'hire male escort Bhopal', 'male escort for events Bhopal', 'male escort for dinner Bhopal', 'male escort for party Bhopal', 'male escort for event Bhopal', 'male escort companion Bhopal', 'male escort company Bhopal', 'male escort service near me', 'male escort booking near me', 'male escort Bhopal city', 'best male escort Bhopal', 'trusted male escort Bhopal', 'professional escort Bhopal', 'professional escort service Bhopal', 'escort companion Bhopal', 'escort and companion Bhopal',
  'male companion for private events Bhopal', 'companion for private event Bhopal', 'male companion for events Bhopal', 'event companion Bhopal', 'private event companion Bhopal', 'event companion service Bhopal', 'companion for party Bhopal', 'male companion for party Bhopal', 'companion for dinner Bhopal', 'dinner companion Bhopal', 'male dinner companion Bhopal', 'companion for social events Bhopal', 'social event companion Bhopal', 'male companion for functions Bhopal', 'companion for functions Bhopal', 'male companion for celebrations Bhopal', 'companion for celebrations Bhopal', 'companion for special occasions Bhopal', 'male companion for special occasions Bhopal', 'professional event companion Bhopal',
  'male companion for dinner Bhopal', 'male companion for lunch Bhopal', 'male companion for coffee Bhopal', 'male companion for outing Bhopal', 'male companion for city tour Bhopal', 'male companion for social outing Bhopal', 'male companion for conversation Bhopal', 'companion for conversation Bhopal', 'one to one companion Bhopal', 'personal meeting companion Bhopal', 'male companion for meeting Bhopal', 'male companion for socializing Bhopal', 'social companionship Bhopal', 'personal companionship Bhopal', 'private companionship Bhopal', 'professional company Bhopal', 'professional male company Bhopal', 'male company for dinner Bhopal', 'male company for events Bhopal', 'male company for outings Bhopal',
  'male massage Bhopal', 'male massage service Bhopal', 'professional male massage Bhopal', 'personal massage Bhopal', 'personal massage service Bhopal', 'relaxation massage Bhopal', 'professional massage Bhopal', 'non sexual massage Bhopal', 'non-sexual male massage Bhopal', 'male relaxation massage Bhopal', 'massage for relaxation Bhopal', 'private massage Bhopal', 'personal massage near me Bhopal', 'male massage near me', 'professional massage near me Bhopal', 'relaxation massage near me Bhopal', 'full body relaxation massage Bhopal', 'back and shoulder massage Bhopal', 'neck and shoulder massage Bhopal', 'Swedish style massage Bhopal',
  'Companios Bhopal', 'Companios male companion', 'Companios Bhopal companion', 'Companios companionship Bhopal', 'Companios massage Bhopal', 'Companios male escort Bhopal', 'Companios escort Bhopal', 'Companios companion service', 'Companios private events', 'Companios booking Bhopal',
  'male companion booking in Bhopal', 'male companion available in Bhopal', 'book male companion Bhopal', 'book a male companion Bhopal', 'male companion appointment Bhopal', 'male companion services in Bhopal', 'male companionship services in Bhopal', 'private companion services Bhopal', 'professional companion services Bhopal', 'trusted companion service Bhopal', 'discreet companion service Bhopal', 'companion service for adults Bhopal', 'adult companion service Bhopal', 'male companion for occasion Bhopal', 'male companion for weekend Bhopal', 'male companion for evening Bhopal', 'male companion for dinner and events Bhopal', 'companion for weekend events Bhopal', 'companion for private gathering Bhopal', 'companion for social gathering Bhopal',
  'what is a male companion service', 'professional male companionship', 'how male companion services work', 'how to book a male companion', 'male companion for events', 'male companion for dinner', 'male companion for social events', 'difference between escort and companion service', 'non sexual male companionship', 'professional companionship services',
]

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: { default: 'Companios Bhopal | Private Male Companionship & Wellness', template: '%s | Companios' },
  description: 'Companios offers professional male companionship, event companionship, and non-sexual wellness experiences in Bhopal, arranged with discretion, clarity, and care.',
  keywords: seoKeywords,
  alternates: { canonical: '/' },
  openGraph: { type: 'website', url: siteUrl, siteName: 'Companios', title: 'Companios Bhopal | Private Male Companionship & Wellness', description: 'Professional male companionship, social support, and restorative wellness experiences in Bhopal.', images: [{ url: '/companios-hero.png', width: 1536, height: 1024, alt: 'A warm, quiet lounge prepared for a private conversation' }] },
  twitter: { card: 'summary_large_image', title: 'Companios Bhopal | Private Male Companionship & Wellness', description: 'Professional male companionship, social support, and restorative wellness experiences in Bhopal.', images: ['/companios-hero.png'] },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1, 'max-video-preview': -1 } },
  icons: { icon: '/icon.svg', apple: '/apple-icon.png' },
}

export const viewport: Viewport = { colorScheme: 'light', themeColor: '#f4f0e9', width: 'device-width', initialScale: 1 }

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const structuredData = { '@context': 'https://schema.org', '@type': 'ProfessionalService', name: 'Companios', url: siteUrl, description: metadata.description, image: `${siteUrl}/companios-hero.png`, areaServed: { '@type': 'City', name: 'Bhopal' }, serviceType: ['Male companionship', 'Private companionship', 'Event companionship', 'Professional wellness and non-sexual massage'] }
  return <html lang="en"><body className={`${serif.variable} ${sans.variable}`}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />{children}{process.env.NODE_ENV === 'production' && <Analytics />}</body></html>
}
